-- CreateEnum
CREATE TYPE "BenchmarkType" AS ENUM ('NORMALIZED', 'PRE_ACTION');

-- CreateTable
CREATE TABLE "Benchmark" (
    "id" SERIAL NOT NULL,
    "buildingId" INTEGER NOT NULL,
    "type" "BenchmarkType" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "january" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "february" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "march" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "april" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "may" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "june" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "july" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "august" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "september" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "october" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "november" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "december" DOUBLE PRECISION NOT NULL DEFAULT 0,

    CONSTRAINT "Benchmark_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Benchmark" ADD CONSTRAINT "Benchmark_buildingId_fkey" FOREIGN KEY ("buildingId") REFERENCES "Building"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
